Repository easyscience/corelib, pull requests merged in 2024-08, with the labels that each got.

#40 Tests for DFO minimizer
  src/easyscience/fitting/__init__.py
  src/easyscience/fitting/minimizers/__init__.py
  src/easyscience/fitting/minimizers/minimizer_base.py
  src/easyscience/fitting/minimizers/minimizer_bumps.py
  src/easyscience/fitting/minimizers/minimizer_dfo.py
  src/easyscience/fitting/minimizers/minimizer_lmfit.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_dfo.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_lmfit.py
Labels: chore

#41 38 add tests for minimizer bumps
  src/easyscience/fitting/fitter.py
  src/easyscience/fitting/minimizers/factory.py
  src/easyscience/fitting/minimizers/minimizer_base.py
  src/easyscience/fitting/minimizers/minimizer_bumps.py
  src/easyscience/fitting/minimizers/minimizer_dfo.py
  src/easyscience/fitting/minimizers/minimizer_lmfit.py
  tests/integration_tests/Fitting/test_fitter.py
  tests/integration_tests/Fitting/test_fitter_legacy_parameter.py
  tests/integration_tests/Fitting/test_multi_fitter.py
  tests/integration_tests/Fitting/test_multi_fitter_legacy_parameter.py
  tests/unit_tests/Fitting/minimizers/test_factory.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_bumps.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_dfo.py
  tests/unit_tests/Fitting/test_fitter.py
  tests/unit_tests/global_object/test_undo_redo.py
Labels: chore

#5 New job
  src/easyscience/Datasets/xarray.py
  src/easyscience/Objects/Job/Theory.py
  src/easyscience/Objects/job/__init__.py
  src/easyscience/Objects/job/analysis.py
  src/easyscience/Objects/job/experiment.py
  src/easyscience/Objects/job/job.py
  src/easyscience/Objects/job/theoreticalmodel.py
Labels: enhancement

#45 minimizer consolidation
  src/easyscience/fitting/minimizers/minimizer_base.py
  src/easyscience/fitting/minimizers/minimizer_bumps.py
  src/easyscience/fitting/minimizers/minimizer_dfo.py
  src/easyscience/fitting/minimizers/minimizer_lmfit.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_base.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_bumps.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_lmfit.py
Labels: chore

#47 slightly reworked API for accessing info about minimizers
  src/easyscience/fitting/minimizers/minimizer_base.py
  src/easyscience/fitting/minimizers/minimizer_bumps.py
  src/easyscience/fitting/minimizers/minimizer_dfo.py
  src/easyscience/fitting/minimizers/minimizer_lmfit.py
  tests/integration_tests/Fitting/test_fitter.py
  tests/integration_tests/Fitting/test_fitter_legacy_parameter.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_base.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_bumps.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_dfo.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_lmfit.py
Labels: enhancement

#49 48 Re-increment unique names if already exists
  src/easyscience/Objects/ObjectClasses.py
  src/easyscience/Objects/Variable.py
  src/easyscience/Objects/new_variable/descriptor_base.py
  tests/unit_tests/Objects/new_variable/test_descriptor_base.py
Labels: bug, borg

#43 27 arithmetic operations for parameters
  src/easyscience/Objects/new_variable/descriptor_number.py
  src/easyscience/Objects/new_variable/parameter.py
  src/easyscience/fitting/minimizers/minimizer_base.py
  tests/unit_tests/Objects/new_variable/test_descriptor_number.py
  tests/unit_tests/Objects/new_variable/test_parameter.py
Labels: enhancement, feature

#56 update version, correct the despatch
  .github/workflows/python-package.yml
  src/easyscience/__version__.py
Labels: fix

#62 58 ensure values are always floats
  src/easyscience/Objects/new_variable/descriptor_number.py
  src/easyscience/Objects/new_variable/parameter.py
  tests/unit_tests/Objects/new_variable/test_parameter.py
Labels: fix

#64 58 ensure values are always floats
  src/easyscience/Objects/new_variable/descriptor_number.py
  src/easyscience/Objects/new_variable/parameter.py
  tests/unit_tests/Objects/new_variable/test_parameter.py
Labels: fix

#67 66 constraints do not seem to work when there is a calculator set
  src/easyscience/Objects/new_variable/parameter.py
  src/easyscience/fitting/Constraints.py
  tests/unit_tests/Fitting/test_constraints.py
Labels: bug

#61 60 add support lmfit differential evolution
  src/easyscience/fitting/__init__.py
  src/easyscience/fitting/available_minimizers.py
  src/easyscience/fitting/fitter.py
  src/easyscience/fitting/minimizers/factory.py
  src/easyscience/fitting/minimizers/minimizer_base.py
  src/easyscience/fitting/minimizers/minimizer_bumps.py
  src/easyscience/fitting/minimizers/minimizer_dfo.py
  src/easyscience/fitting/minimizers/minimizer_lmfit.py
  tests/integration_tests/Fitting/test_fitter.py
  tests/integration_tests/Fitting/test_fitter_legacy_parameter.py
  tests/unit_tests/Fitting/minimizers/test_factory.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_base.py
  tests/unit_tests/Fitting/minimizers/test_minimizer_lmfit.py
  tests/unit_tests/Fitting/test_fitter.py
Labels: chore
